import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";

import {
  buildGtmReadinessReport,
  formatGtmReadinessReport,
  verifyManifestLines
} from "../scripts/gtm-readiness-check.mjs";

const execFileAsync = promisify(execFile);
const scriptPath = fileURLToPath(new URL("../scripts/gtm-readiness-check.mjs", import.meta.url));

function sha256(text) {
  return createHash("sha256").update(text).digest("hex");
}

async function createPack(files) {
  const dir = await mkdtemp(join(tmpdir(), "dema-gtm-pack-"));
  await mkdir(dir, { recursive: true });
  const lines = [];
  for (const [name, body] of Object.entries(files)) {
    await writeFile(join(dir, name), body, "utf8");
    lines.push(`${sha256(body)}  ${name}`);
  }
  await writeFile(join(dir, "MANIFEST.sha256"), `${lines.join("\n")}\n`, "utf8");
  return dir;
}

test("buildGtmReadinessReport verifies current GTM docs and Lighthouse pack boundaries", async () => {
  const packDir = await createPack({
    "00_START_HERE.md": "start\n",
    "08_INVITATION_DRAFT.md": "private invitation\n"
  });
  try {
    const report = await buildGtmReadinessReport({ lighthousePackDir: packDir });

    assert.equal(report.schema, "bizra.dema.gtm_readiness_check.v0.1");
    assert.equal(report.mode, "READ_ONLY_AUDIT");
    assert.equal(report.ok, true);
    assert.equal(report.boundary.runtime_execution, false);
    assert.equal(report.boundary.receipt_minted, false);
    assert.equal(report.boundary.send_performed, false);
    assert.equal(report.lighthouse_pack.ok, true);
    assert.equal(report.findings.length, 0);
    assert.ok(report.checks.some((check) => check.name === "phase1_packet_required_phrases" && check.ok));
    assert.ok(report.checks.some((check) => check.name === "gtm_current_state_markers" && check.ok));
  } finally {
    await rm(packDir, { recursive: true, force: true });
  }
});

test("verifyManifestLines catches tampered Lighthouse pack content", async () => {
  const packDir = await createPack({ "00_START_HERE.md": "start\n" });
  try {
    await writeFile(join(packDir, "00_START_HERE.md"), "tampered\n", "utf8");
    const result = await verifyManifestLines({
      dir: packDir,
      manifestText: `${sha256("start\n")}  00_START_HERE.md\n`
    });

    assert.equal(result.ok, false);
    assert.deepEqual(result.entries.map((entry) => entry.status), ["mismatch"]);
  } finally {
    await rm(packDir, { recursive: true, force: true });
  }
});

test("verifyManifestLines ignores sha256sum-compatible comment lines", async () => {
  const packDir = await createPack({ "00_START_HERE.md": "start\n" });
  try {
    const result = await verifyManifestLines({
      dir: packDir,
      manifestText: [
        "# Lighthouse Pack v1.0 · SHA-256 manifest",
        "# Generated by pack ceremony",
        `${sha256("start\n")}  00_START_HERE.md`
      ].join("\n")
    });

    assert.equal(result.ok, true);
    assert.equal(result.entry_count, 1);
    assert.deepEqual(result.entries.map((entry) => entry.status), ["ok"]);
  } finally {
    await rm(packDir, { recursive: true, force: true });
  }
});

test("formatGtmReadinessReport renders concise human output", async () => {
  const packDir = await createPack({ "00_START_HERE.md": "start\n" });
  try {
    const output = formatGtmReadinessReport(
      await buildGtmReadinessReport({ lighthousePackDir: packDir })
    );

    assert.match(output, /DEMA GTM Readiness Check/);
    assert.match(output, /Result: PASS/);
    assert.match(output, /Boundary: read-only audit; no send; no runtime; no receipt mint/);
  } finally {
    await rm(packDir, { recursive: true, force: true });
  }
});

test("gtm-readiness-check script supports --json", async () => {
  const packDir = await createPack({ "00_START_HERE.md": "start\n" });
  try {
    const { stdout } = await execFileAsync("node", [
      scriptPath,
      "--json",
      "--lighthouse-pack-dir",
      packDir
    ]);
    const report = JSON.parse(stdout);

    assert.equal(report.schema, "bizra.dema.gtm_readiness_check.v0.1");
    assert.equal(report.ok, true);
    assert.equal(report.lighthouse_pack.ok, true);
  } finally {
    await rm(packDir, { recursive: true, force: true });
  }
});
